import { Poppins } from "next/font/google";
import "./globals.css";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import InfoNav from "@/Components/InfoNav";
import Header from "@/Components/Header";
import Advertisement from "@/Components/Advertisement";
import Footer from "@/Components/Footer";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Grocer Point",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${poppins.className} bg-gray-50`}>
        <InfoNav />
        <Header />
        <main className="container-width px-2 lg:px-6">
          {children}
        </main>
        <Advertisement />
        <Footer />
      </body>
    </html>
  );
}
